// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-lL98Df3sUBPRX4RzxZ_Fl31uyYqf1V8',
    appId: '1:51443322991:web:2df87f5b197fad268bbd9a',
    messagingSenderId: '51443322991',
    projectId: 'lmgtask-ac5ab',
    authDomain: 'lmgtask-ac5ab.firebaseapp.com',
    storageBucket: 'lmgtask-ac5ab.firebasestorage.app',
    measurementId: 'G-5HWE02HK34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpIw5Ieg8udiGsCZ3joRAZHTzSI-_l5g',
    appId: '1:51443322991:android:28a51eccca9ec3e88bbd9a',
    messagingSenderId: '51443322991',
    projectId: 'lmgtask-ac5ab',
    storageBucket: 'lmgtask-ac5ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe449vQAWYCJ20MnNlS9Jms3PkyvETEW0',
    appId: '1:51443322991:ios:24e390f871412dcd8bbd9a',
    messagingSenderId: '51443322991',
    projectId: 'lmgtask-ac5ab',
    storageBucket: 'lmgtask-ac5ab.firebasestorage.app',
    iosBundleId: 'com.example.lmgtodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe449vQAWYCJ20MnNlS9Jms3PkyvETEW0',
    appId: '1:51443322991:ios:24e390f871412dcd8bbd9a',
    messagingSenderId: '51443322991',
    projectId: 'lmgtask-ac5ab',
    storageBucket: 'lmgtask-ac5ab.firebasestorage.app',
    iosBundleId: 'com.example.lmgtodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-lL98Df3sUBPRX4RzxZ_Fl31uyYqf1V8',
    appId: '1:51443322991:web:b931035d193864778bbd9a',
    messagingSenderId: '51443322991',
    projectId: 'lmgtask-ac5ab',
    authDomain: 'lmgtask-ac5ab.firebaseapp.com',
    storageBucket: 'lmgtask-ac5ab.firebasestorage.app',
    measurementId: 'G-S04G1F88VE',
  );
}
